name: Continuous Delivery

on:
  push:
    branches: [ main ]

jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Core Service
        uses: docker/build-push-action@v2
        with:
          tags: sominola/cvbuilder.frontend:latest
          context: .
          file: Dockerfile
          push: true
